USE SAKILA;

SELECT * FROM FILM;
SELECT * FROM FILM_ACTOR;
SELECT * FROM FILM_CATEGORY;

# EJ1.- ¿CUÁLES SON LAS TARIFAS DE ALQUILER (RENTAL RATE)?
SELECT DISTINCT RENTAL_RATE AS TARIFAS_ALQUILER FROM FILM;

# EJ2.- ¿CUÁNTAS PELÍCULAS DURAN MÁS DE 100 MINUTOS Y TIENEN UN RATING DE PG, R O G?
SELECT COUNT(*) FROM FILM WHERE (LENGTH >100) AND (RATING = "PG" OR "R" OR "G"); #RECUENTO DE CUANTAS PELICULAS.

# EJ3.- ¿CUÁL ES LA PELÍCULA O PELÍCULAS CON MAYOR DURACIÓN DE LAS QUE CONTIENEN TRAILERS COMO EXTRAS?
SELECT TITLE FROM FILM WHERE SPECIAL_FEATURES LIKE "%Trailers%" ORDER BY LENGTH DESC LIMIT 3;

# EJ4.- ¿QUÉ PELÍCULAS ESTÁN PROTAGONIZADAS POR UN ASTRONAUTA Y UN ADMINSTRADOR DE BASES DE DATOS (DESCRIPTION)?

SELECT * FROM FILM WHERE DESCRIPTION LIKE "%Astronaut%" OR "%Database Administrator%"; ####

# EJ5.- ¿CUÁNTO DURAN, DE MEDIA, LAS PELÍCULAS PROTAGONIZADAS POR EL ACTOR 1 (FILM_ACTOR)?
# EJ6.- ¿CUÁNTO TARDARÍAMOS (EN HORAS) EN VER TODAS LAS PELÍCULAS DE CATEGORÍA 6 (FILM_CATEGORY)?