DROP SCHEMA IF EXISTS POKEMON;
CREATE SCHEMA POKEMON;
USE POKEMON;

CREATE TABLE ENTRENADOR (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 NOMBRE VARCHAR(50) NOT NULL,
 TIPO VARCHAR(50) NOT NULL,
 NIVEL TINYINT,
 ID_ENTRENADOR INT,
 FECHA_HORA_CAPTURA DATETIME,
 POKEBALLS_USADAS TINYINT,
 
 FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR(ID),
 CONSTRAINT LIMITE_POKEBALLS CHECK (POKEBALLS_USADAS BETWEEN 1 AND 5)
);

CREATE TABLE GIMNASIO (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50),
CIUDAD VARCHAR(50),
MEDALLA_OTORGADA VARCHAR(50),

FOREIGN KEY (MEDALLA_OTORGADA) REFERENCES MEDALLA(ID)
);

CREATE TABLE MEDALLA (
ID INT PRIMARY KEY AUTO_INCREMENT,
FECHA_OBTENCION DATE,
NOMBRE VARCHAR(50),
ID_ENTRENADOR INT,
ID_GIMNASIO INT,

FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR(ID),
FOREIGN KEY (ID_GIMNASIO) REFERENCES GIMNASIO(ID)
);

CREATE TABLE ENTRENADOR_DESAFIA_FIMNASIO (
ID_ENTRENADOR INT,
ID_GIMNASIO INT,
FECHA DATE,

PRIMARY KEY (ID_ENTRENADOR,ID_GIMNASIO,FECHA),
FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR (ID),
FOREIGN KEY (ID_GIMNASIO) REFERENCES GIMNASIO (ID)
);

INSERT INTO GIMNASIO VALUES
(DEFAULT, "GIMNASIO VERDE", DEFAULT, 3)

INSERT INTO POKEMON VALUES
(DEFAULT, "CHARMANDER", "INSTAHOTTIE", 14, 1, "2023-05-12",2),
(DEFAULT, "CHARMANDER", "INSTAHOTTIE", 14, 1, "2023-05-12",2),
(DEFAULT, "CHARMANDER", "INSTAHOTTIE", 14, 1, "2023-05-12",2),
(DEFAULT, "CHARMANDER", "INSTAHOTTIE", 14, 1, "2023-05-12",2)


INSERT INTO ENTRENADOR_DESAFIA_GIMNASIO VALUES
()

INSERT INTO MEDALLA VALUES
(DEFAULT, "2023-05-15","MEDALLA VERDE",1,1)


