DROP SCHEMA IF EXISTS RESTAURANTE;
CREATE SCHEMA RESTAURANTE;
USE RESTAURANTE;

CREATE TABLE CATEGORIA (
	NOMBRE VARCHAR(30) PRIMARY KEY,
    DESCRIPCION TINYTEXT
);


CREATE TABLE PLATO (
	NOMBRE VARCHAR(30) PRIMARY KEY,
    DESCRIPCION TINYTEXT,
    FOTO MEDIUMBLOB,
    PRECIO DECIMAL(5,2),
    NOMBRE_CATEGORIA VARCHAR(30),
    FOREIGN KEY (NOMBRE_CATEGORIA) REFERENCES CATEGORIA(NOMBRE)

);

CREATE TABLE RECETA (
	CODIGO VARCHAR(30) PRIMARY KEY,
    TIEMPO_ELABORACION TIME,
    DIFICULTAD VARCHAR(15),
    NOMBRE_PLATO VARCHAR(30),
    FOREIGN KEY (NOMBRE_PLATO) REFERENCES PLATO(NOMBRE)

);

CREATE TABLE INGREDIENTE (
	NOMBRE VARCHAR(30) PRIMARY KEY,
    FOTO MEDIUMBLOB,
    STOCK DECIMAL (5,2)
);

CREATE TABLE RECETA_USA_INGREDIENTE (
	CODIGO VARCHAR(30),
    NOMBRE VARCHAR(30),
    CANTIDAD DECIMAL(5,2),
    UNIDAD_DE_MEDIDA VARCHAR(15),
    
    PRIMARY KEY (CODIGO, NOMBRE),
    FOREIGN KEY (CODIGO) REFERENCES RECETA(CODIGO),
    FOREIGN KEY (NOMBRE) REFERENCES INGREDIENTE(NOMBRE)
  
);
    
	