DROP SCHEMA IF EXISTS CONCESIONARIOCOCHES;
CREATE SCHEMA CONCESIONARIOCOCHES;
USE CONCESIONARIOCOCHES;

CREATE TABLE MARCA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50)

);

CREATE TABLE MODELO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    ID_MARCA INT,
    
    FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID)

);

CREATE TABLE VERSION (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    POTENCIA SMALLINT,
    PRECIO DECIMAL,
    COMBUSTIBLE VARCHAR(10),
    ID_MODELO INT,
    
    FOREIGN KEY (ID_MODELO) REFERENCES MODELO(ID)
    
    
);

CREATE TABLE EXTRA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    DESCRIPCION MEDIUMTEXT
);

CREATE TABLE CLIENTE (
	NIF CHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(50),
    DIRECCION VARCHAR(50),
    TELEFONO VARCHAR(15)
);

CREATE TABLE VENDEDOR (
	NIF CHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(50),
    DIRECCION VARCHAR(50),
    TELEFONO VARCHAR(15)
);

CREATE TABLE VERSION_EQUIPA_EXTRA (
	ID_VERSION INT,
    ID_EXTRA INT,
    PRECIO DECIMAL(9,2),
    
    PRIMARY KEY(ID_VERSION,ID_EXTRA),
    
    FOREIGN KEY (ID_VERSION) REFERENCES VERSION(ID),
    FOREIGN KEY (ID_EXTRA) REFERENCES EXTRA(ID)
    
);

CREATE TABLE CLIENTE_COMPRA_MODELO (
	NIF_CLIENTE CHAR(9),
    ID_MODELO INT,
    FECHA_COMPRA DATE,
    MATRICULA VARCHAR(10),
    NIF_VENDEDOR CHAR(9),
    
    PRIMARY KEY (NIF_CLIENTE, ID_MODELO, MATRICULA),
    
    FOREIGN KEY (NIF_CLIENTE) REFERENCES CLIENTE(NIF),
    FOREIGN KEY (ID_MODELO) REFERENCES MODELO(ID),
    FOREIGN KEY (NIF_VENDEDOR) REFERENCES VENDEDOR(NIF)

);