DROP SCHEMA IF EXISTS ZOO; 			#-----------EHTO QUE EHHHS?
CREATE SCHEMA ZOO;
USE ZOO;

# RESTRICCIONES:
#
#	- DESCRIPCION Y NOMBRE COMUN NO PUEDEN SER NULOS
#    - EL CLIMA POR DEFECTO ES "SOLEADO"
#    - EL TIEMPO DEL RECORRIDO DEBE SER MAYOR DE 30 MINUTOS
#    - LA LONGITUD DEL RECORRIDO MO PUEDE SER NEGATIVA
#    - EL INDICE DE VULNERABILIDAD ES UN NUMERO ENTR 0 Y 10 
    


CREATE TABLE ESPECIE (
	NOMBRE_CIENTIFICO VARCHAR(30) PRIMARY KEY,
    DESCRIPCION TINYTEXT,
    FOTO MEDIUMBLOB
);
INSERT INTO ESPECIE VALUES
("MUSTELA PUTORUS FURO", "MUSTELIDO DOMESTICADO", NULL);

CREATE TABLE ESPECIE_TIENE_NOMBRE_COMUN (
	NOMBRE_COMUN VARCHAR(30) PRIMARY KEY,
    NOMBRE_CIENTIFICO VARCHAR(30)
);

CREATE TABLE RECORRIDO (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    LONGITUD DECIMAL (5,2) UNSIGNED,
    TIEMPO TIME,
    MAXVISITANTES MEDIUMINT,
    CONSTRAINT TIEMPO_MAYOR CHECK (TIEMPO>"00:30:00"), 
    CONSTRAINT LONGITUD_MINIMA CHECK (LONGITUD>0)
    
);

INSERT INTO RECORRIDO VALUES
(DEFAULT, 300, "00:50:00", 40);

CREATE TABLE HABITAT (
	NOMBRE_HABITAT VARCHAR(30) PRIMARY KEY,
    CLIMA VARCHAR(30) DEFAULT "SOLEADO",
    VEGETACION VARCHAR(30),
    CODIGO_RECORRIDO INT,
    
    FOREIGN KEY (CODIGO_RECORRIDO) REFERENCES RECORRIDO(CODIGO)
);

INSERT INTO HABITAT VALUES
("BOSQUE CONTINENTAL", "TEMPLADO", "MATORRAL", 1);

CREATE TABLE ESPECIE_VIVE_HABITAT (
	NOMBRE_HABITAT VARCHAR(50),
    NOMBRE_CIENTIFICO VARCHAR(50),
    INDICE_VULNERABILIDAD TINYINT,
	
    
    PRIMARY KEY (NOMBRE_CIENTIFICO, NOMBRE_HABITAT),
    FOREIGN KEY (NOMBRE_CIENTIFICO) REFERENCES ESPECIE(NOMBRE_CIENTIFICO),
    FOREIGN KEY (NOMBRE_HABITAT) REFERENCES HABITAT(NOMBRE_HABITAT),
    CONSTRAINT VULNERABILIDAD_0_10 CHECK (INDICE_VULNERABILIDAD>=0 AND INDICE_VULNERABILIDAD<=10)
	#CONSTRAINT VULNERABILIDAD_0_10 CHECK (INDICE_VULNERABILIDAD BETWEEN 0 AND 10)
);
    
INSERT INTO ESPECIE_VIVE_HABITAT VALUES
("MUSTELA PUTORUS FURO", "BOSQUE CONTINENTAL", 3);

SELECT * FROM ESPECIE;
