DROP SCHEMA IF EXISTS ANUNCIOWEB;
CREATE SCHEMA ANUNCIOWEB;
USE ANUNCIOWEB;


# RESTRICCIONES:
#	Email y telefono deben ser unicos
#	precio debe ser nmayor que 0
#	las columnas NOMBRE no pueden ser nulas
#	la fecha de fin debe ser posterior a la fecha de inicio
#	el contenido por defecto es CONTENIDO MARCA ACME

CREATE TABLE CLIENTE (
	
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(30) NOT NULL,
    DIRECCION VARCHAR(50),
    TELEFONO INT UNIQUE,
    EMAIL VARCHAR(30) UNIQUE


);

CREATE TABLE ANUNCIO (
	ID_ANUNCIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(30) NOT NULL,
    TITULO VARCHAR(30),
    CONTENIDO MEDIUMTEXT DEFAULT "CONTENIDO MARCA ACME",
    CATEGORIA VARCHAR(30),
    PRECIO DECIMAL (9,2) ,
    ID_CLIENTE INT,
    
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT PRECIO_POSITIVO CHECK (PRECIO>0)
);
    
CREATE TABLE WEB (
	URL_WEB VARCHAR(250) PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    TOPICO VARCHAR(30)
   
);

CREATE TABLE ANUNCIO_APARECE_WEB (

	ID_ANUNCIO INT,
    URL_WEB VARCHAR(255),
    FECHA_INICIO DATETIME,
    FECHA_FIN DATETIME,
    
    
	PRIMARY KEY (ID_ANUNCIO,URL_WEB),
    FOREIGN KEY (ID_ANUNCIO) REFERENCES ANUNCIO(ID_ANUNCIO),
    FOREIGN KEY (URL_WEB) REFERENCES WEB(URL_WEB),
    
    CONSTRAINT FECHA_OK CHECK (FECHA_FIN>FECHA_INICIO)
    
);
	