USE SAKILA;

SELECT * FROM FILM;

# EJ1 MUESTRA LA PELICULA MAS LARGA
SELECT * FROM FILM ORDER BY LENGTH DESC LIMIT 1;

# EJ2 MUESTRA LA PELICULA CON MENOR DURACION
SELECT * FROM FILM ORDER BY LENGTH ASC LIMIT 1;

# EJ3 MUESTRA LOS DISTINTOS RATING DE EDAD USADOS
SELECT DISTINCT RATING FROM FILM;

# EJ4 CUANTAS PELICULAS DURAN MAS DE DOS HORAS
SELECT * FROM FILM WHERE LENGTH > 120 ORDER BY LENGTH ASC LIMIT 10;

# EJ5 MUESTRA EL NOMBRE DE LAS PELICULAS Y SU DURACION EN HORAS (DE MENOR A MAYOR)

SELECT TITLE, LENGTH/60 FROM FILM ORDER BY LENGTH ASC;

# EJ6 CUANTAS PELICULAS CONTIENEN ESCENAS ELIMINADAS

SELECT COUNT(*) FROM FILM WHERE SPECIAL_FEATURES LIKE "%Deleted Scenes%";

# EJ7 QUE PELICULAS TIENEN "ALIEN" EN SU NOMBRE? (ORDEN ALFABETICO)
SELECT * FROM FILM WHERE TITLE LIKE "%Alien%" ORDER BY TITLE DESC;
# EJ8 CUAL ES LA PELICULA MAS LARGA QUE PODEMOS VER POR MENOS DE 1$ (RENTALRATE)

SELECT TITLE, LENGTH, RENTAL_RATE FROM FILM WHERE RENTAL_RATE<1.01 ORDER BY LENGTH DESC LIMIT 10;

# EJ9 CUANTAS PELICULAS SON DOCUMENTALES

SELECT TITLE, DESCRIPTION FROM FILM WHERE DESCRIPTION LIKE "%Documentary%";
# EJ10 CUAL ES EL PRECIO DE REEMPLAZO MEDIO DE LAS PELICULAS CON RATING "R"?
SELECT AVG(REPLACEMENT_COST) FROM FILM WHERE RATING = "R";

# EJ11 CUANTOS DIAS TARDARIAMOS EN VER TODAS LAS PELICULAS? Y ANIOS?

SELECT SUM(LENGTH)/60/24 AS DIAS, SUM(LENGTH)/60/24/365 AS ANOS FROM FILM;
